config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {registrations: "registrations"}

  root to: 'home#index'
  devise_scope :employee do
    get '/' => 'devise/sessions#new'
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  resources :employees
  resources :projects do
    collection do
      patch :assign_project
    end
    member do
      get :pie_chart
    end
    resources :features
  end

  get '/manager_features_view' => 'features#manager_features_view'
  get '/todo_list' => 'features#todo_list'
  get '/move_forword/:id' => 'features#move_forword', as: :move_forword
  get '/move_back/:id' => 'features#move_back', as: :move_back

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :developers, class_name: 'Employee', foreign_key: 'manager_id'
  belongs_to :manager, class_name: 'Employee'
  has_many :managing_projects, class_name: 'Project', foreign_key: 'manager_id'
  has_many :projects, through: :assignees
  has_many :assignees
  has_many :features, foreign_key: 'developer_id'

  after_create :assign_default_role

  def assign_default_role
    unless self.email == 'test@projectmanagement.com'
      self.add_role(:developer) if self.roles.blank?
      manager = Employee.joins(:roles).where('roles.name = ?', 'manager')
      self.update_attributes(manager_id: manager.first.id)
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_employee!
  load_and_authorize_resource
  before_action :find_emaployee, only: [:edit, :update]
  def index
    @employees = Employee.all
  end

  def edit
  end

  def update
    role = @employee.roles.first.name
    if @employee.present?
      @employee.roles.destroy_all
      @employee.add_role params[:role].to_sym
      redirect_to employees_path, notice: 'Role updated successfully.'
    else
      redirect_to edit_employee_path(@employee), alert: 'Error while updating role.'
    end
  end

  private

  def find_emaployee
    @employee = Employee.find(params[:id])
  end
end

app/views/employees/edit.html.erb
<div class="row">
  <div class="col-md-12" id="tab_2">
    <div class="portlet box green">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-pencil badge-warning"></i>Change Role
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse"></a>
        </div>
      </div>
      <div class="portlet-body form">
        <%= form_tag(employee_path(@employee), method: 'PATCH') do |f| %>
          <div class=form-body>
            <div class='row'>
              <div class='col-md-6'>
                <label class="control-label">Role</label>
                <%= select_tag :role, options_for_select(['manager', 'developer']), {:prompt => "Select Role", :class => "form-control"} %>
              </div>
            </div>
          </div>
          <div class='form-actions fluid'>
            <div class="row">
              <dir class="col-md-6">
                <%= submit_tag 'Update', class: 'btn btn-primary pull-right' %>
              </dir>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
      <div class="portlet-body form">
        <table  class="table table-striped table-bordered table-hover no-footer" role="grid">
          <thead>
            <tr role="row" class='columnWrap'>
              <th>Name</th>
              <th>Role</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td><%= employee.first_name || employee.email %></td>
                <td><%= employee.roles.first.name %></td>
                <td><%= link_to 'Change Role', edit_employee_path(employee.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>