config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {registrations: "registrations"}

  root to: 'home#index'
  devise_scope :employee do
    get '/' => 'devise/sessions#new'
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  resources :employees
  resources :projects do
    collection do
      patch :assign_project
    end
    member do
      get :pie_chart
    end
    resources :features
  end

  get '/manager_features_view' => 'features#manager_features_view'
  get '/todo_list' => 'features#todo_list'
  get '/move_forword/:id' => 'features#move_forword', as: :move_forword
  get '/move_back/:id' => 'features#move_back', as: :move_back

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :manager, class_name: 'Employee'
  has_many :assignees
  has_many :employees, through: :assignees
  has_many :features

  validates :title, presence: true, uniqueness: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_employee!
  before_action :authorize_employee
  before_action :find_project, only: [:edit, :update, :assign_project, :show, :pie_chart]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(projects_params)
    if @project.save
      redirect_to projects_path, notice: 'Project Created Successfully'
    else
      redirect_to new_project_path, alert: @project.errors.full_messages.join('<br>')
    end
  end

  def index
    @projects = Project.where(manager_id: current_employee.id).order('created_at desc')
  end

  def edit
  end

  def update
    if @project.update_attributes(projects_params)
      redirect_to projects_path, notice: 'Project Updated Successfully'
    else
      redirect_to edit_project_path(@project), alert: @project.errors.full_messages.join('<br>')
    end
  end

  def show
    @employees = Employee.joins(:roles).where('roles.name = ?', 'developer')
  end

  def assign_project
    if params[:developers].present? 
      Assignee.transaction do
        params[:developers].each do |developer|
          Assignee.find_or_create_by(employee_id: developer, project_id: @project.id)
        end
      end
      redirect_to projects_path, notice: 'Assigned Successfully'
    else
      redirect_to project_path(@project.id), alert: "Please select atleast on developer"
    end
  end

  def pie_chart
    features = @project.features
    @todo = features.by_status(@project.id, 'todo').count
    @inprogress = features.by_status(@project.id, 'inprogress').count
    @done = features.by_status(@project.id, 'done').count
  end

  private

  def authorize_employee
    authorize! :manage, Project
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def projects_params
    params.require(:project).permit(:title, :description, :manager_id)
  end
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-md-12" id="tab_2">
    <div class="portlet box green">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-pencil badge-warning"></i><%= @project.new_record? ? 'Add Project' : 'Edit Project' %>
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse"></a>
        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
          <div class=form-body>
            <div class='row'>
              <div class='col-md-6'>
                <label class="control-label">Title
                  <span class="required" aria-required="true">* </span>
                </label>
                <%= f.text_field :title, class: 'form-control' %>
              </div>
              <div class='col-md-6'>
                <label class="control-label">Description
                </label>
                <%= f.text_area :description, size: '5 x 5' , class: 'form-control' %>
              </div>
              <%= f.hidden_field :manager_id, value: current_employee.id %>
            </div>
          </div>
          <div class='form-actions fluid'>
            <% if @project.new_record? %>
              <%= f.submit 'Create Project', class: 'btn primary pull-right margin-top-15' %>
            <% else %>
              <%= f.submit 'Update', class: 'btn primary pull-right margin-top-15' %>
            <% end %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%= link_to 'New Project', new_project_path, class: 'pull-right btn btn-primary margin-bottom-30' %>
<div class="row">
  <div class="">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>
            Title
          </th>
          <th>
            Action
          </th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td>
              <%= project.title %>
            </td>
            <td>
              <%= link_to 'Edit', edit_project_path(project) %> | 
              <%= link_to 'Assign Project', project_path(project.id) %> | 
              <%= link_to 'Add New Feature', new_project_feature_path(project.id) %> | 
              <%= link_to 'Features', project_features_path(project.id) %> | 
              <%= link_to 'Pie Chart', pie_chart_project_path(project.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/pie_chart.html.erb
<script type="text/javascript">
// Load the Visualization API and the corechart package.
google.charts.load('current', {'packages':['corechart']});

// Set a callback to run when the Google Visualization API is loaded.
google.charts.setOnLoadCallback(drawChart);

// Callback that creates and populates a data table,
// instantiates the pie chart, passes in the data and
// draws it.
function drawChart() {

// Create the data table.
  var data = new google.visualization.DataTable();
  data.addColumn('string', 'Status');
  data.addColumn('number', 'Features');
  data.addRows([
    ['ToDo', parseInt('<%= @todo %>')],
    ['In Progress', parseInt('<%= @inprogress %>')],
    ['Done', parseInt('<%= @done %>')]
  ]);

// Set chart options
  var options = {'title':'Status of Features in <%= @project.title %>',
                 'width':600,
                 'height':500};
// Instantiate and draw our chart, passing in some options.
  var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
  chart.draw(data, options);
}
  
</script>
<!--Div that will hold the pie chart-->
<div id="chart_div"></div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-12" id="tab_2">
    <div class="portlet box green">
      <div class="portlet-body form">
        <%= form_tag(assign_project_projects_path, method: 'PATCH', html: {class: "form-horizontal"}) do %>
          <div class=form-body>
            <div class='row'>
              <div class='col-md-6'>
                <label class="control-label">Users
                  <span class="required" aria-required="true">* </span>
                </label>
                <%= select_tag :developers, options_from_collection_for_select(@employees, 'id', 'email'), multiple: true, class: 'form-control' %>
	              <%= hidden_field_tag :id, params[:id] %>
              </div>
            </div>
          </div>
          <div class='form-actions fluid'>
          	<div class="row">
          		<div class="col-md-6">
	            	<%= submit_tag 'Assign', class: 'btn primary pull-right margin-top-15' %>
		          </div>
          	</div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>