config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {registrations: "registrations"}

  root to: 'home#index'
  devise_scope :employee do
    get '/' => 'devise/sessions#new'
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  resources :employees
  resources :projects do
    collection do
      patch :assign_project
    end
    member do
      get :pie_chart
    end
    resources :features
  end

  get '/manager_features_view' => 'features#manager_features_view'
  get '/todo_list' => 'features#todo_list'
  get '/move_forword/:id' => 'features#move_forword', as: :move_forword
  get '/move_back/:id' => 'features#move_back', as: :move_back

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :developer, class_name: 'Employee'
  belongs_to :project
  scope :by_status_project_developer, ->(project_id, developer_id, status) { where(status: status, project_id: project_id, developer_id: developer_id)}
  scope :status_by_project_manager, ->(project_id, status) { where(status: status, project_id: project_id)}
  scope :by_status, -> (project_id, status){where(status: status, project_id: project_id)}
  
  validates :title, presence: true
  validates :developer_id, presence: true
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_employee!
  before_action :authorize_employee, except: [:todo_list, :move_back, :move_forword]
  before_action :find_feature, only: [:edit, :update, :move_forword, :move_back]
  before_action :find_project, except: [:todo_list, :move_back, :move_forword, :manager_features_view]

  def new
    @feature = Feature.new
  end

  def create
    @feature = Feature.new(features_params)
    if @feature.save
      redirect_to project_features_path, notice: 'Feature Created Successfully'
    else
      redirect_to new_project_feature_path, alert: @feature.errors.full_messages.join('<br>')
    end
  end

  def index
    @features = @project.features.order('created_at desc')
  end

  def edit
  end

  def update
    if @feature.update_attributes(features_params)
      redirect_to project_features_path, notice: 'Feature Updated Successfully'
    else
      redirect_to edit_project_feature_path(@project, @feature), alert: @feature.errors.full_messages.join('<br>')
    end
  end

  def todo_list
    authorize! :view, :todo_list
    @projects = current_employee.projects
  end

  def move_forword
    authorize! :write, :move_forword
    case @feature.status
    when 'todo'
      @feature.update_attributes(status: 'inprogress')
      @message = { notice: "#{@feature.title} moved to In Progress", feature: @feature.id}
    when 'inprogress'
      @feature.update_attributes(status: 'done')
      @message = { notice: "#{@feature.title} moved to Done", feature: @feature.id}
    else
      @message = { alert: "#{@feature.title} can not be move forword."}
    end
  end

  def move_back
    authorize! :write, :move_back
    case @feature.status
    when 'done'
      @feature.update_attributes(status: 'inprogress')
      @message = { notice: "#{@feature.title} moved to In Progress", feature: @feature.id}
    when 'inprogress'
      @feature.update_attributes(status: 'todo')
      @message = { notice: "#{@feature.title} moved to ToDo", feature: @feature.id}
    else
      @message = { alert: "#{@feature.title} can not be move backword."}
    end
  end

  def manager_features_view
    @projects = current_employee.managing_projects
  end

  private

  def authorize_employee
    authorize! :manage, Feature
  end

  def find_feature
    @feature = Feature.find(params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def features_params
    params.require(:feature).permit(:title, :description, :developer_id, :status, :project_id)
  end
end

app/views/features/_form.html.erb
<div class="row">
  <div class="col-md-12" id="tab_2">
    <div class="portlet box green">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-pencil badge-warning"></i><%= @feature.new_record? ? 'Add Feature' : 'Edit Feature' %>
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse"></a>
        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for([@project, @feature], html: {class: "form-horizontal"}) do |f| %>
          <div class=form-body>
            <div class='row'>
              <div class='col-md-6'>
                <label class="control-label">Title
                  <span class="required" aria-required="true">* </span>
                </label>
                <%= f.text_field :title, class: 'form-control' %>
              </div>
              <div class='col-md-6'>
                <label class="control-label">Description
                </label>
                <%= f.text_area :description, size: '5 x 5' , class: 'form-control' %>
              </div>
              <div class='col-md-6'>
                <label class="control-label">Developer
                </label>
                <%= f.select :developer_id, options_for_select(@project.employees.collect {|p| [ p.email, p.id ] }), {:prompt => "Select Developer", :class => "form-control", :selected => @feature.developer} %>
              </div>
              <%= f.hidden_field :project_id, value: params[:project_id] %>
            </div>
          </div>
          <div class='form-actions fluid'>
            <% if @feature.new_record? %>
              <%= f.submit 'Create Feature', class: 'btn primary pull-right margin-top-15' %>
            <% else %>
              <%= f.submit 'Update', class: 'btn primary pull-right margin-top-15' %>
            <% end %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/features/edit.html.erb
<%= render 'form' %>

app/views/features/index.html.erb
<%= link_to 'New Feature', new_project_feature_path(@project), class: 'pull-right btn btn-primary margin-bottom-30' %>
<div class="row">
  <div class="">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>
            Title
          </th>
          <th>
            Description
          </th>
          <th>
            Developer
          </th>
          <th>
            Action
          </th>
        </tr>
      </thead>
      <tbody>
        <% @features.each do |feature| %>
          <tr>
            <td>
              <%= feature.title %>
            </td>
            <td>
              <%= feature.description %>
            </td>
            <td>
              <%= feature.developer.email %>
            </td>
            <td>
              <%= link_to 'Edit', edit_project_feature_path(@project, feature) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/features/manager_features_view.html.erb
<div class="alert alert-success alert-danger alert-dismissable hidden" id="feature-messages">
  <span id="response-message"></span>
</div>
<div class="row">
  <div class="">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>
            Status
          </th>
          <% @projects.each do |project| %>
            <th>
              <%= project.title %>
            </th>
          <% end %>  
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>ToDo</td>
          <% @projects.each do |project| %>
            <% todo_features =  Feature.status_by_project_manager(project.id, 'todo') %>
            <td>
              <% todo_features.each do |todo| %>
                <%= todo.title %> ( <%= todo.developer.email %> )
              <% end %>          
            </td>         
          <% end %>
        </tr>
        <tr>
          <td>In Progress</td>
          <% @projects.each do |project| %>
            <% inprogress_features =  Feature.status_by_project_manager(project.id, 'inprogress') %>
            <td>
              <% inprogress_features.each do |inprogress| %>
                <%= inprogress.title %> ( <%= inprogress.developer.email %> )
              <% end %>          
            </td>
          <% end %>
        </tr>
        <tr>
          <td>Done</td>
          <% @projects.each do |project| %>
            <% done_features =  Feature.status_by_project_manager(project.id, 'done') %>
            <td>
              <% done_features.each do |done| %>
                <%= done.title %> ( <%= done.developer.email %> )
              <% end %>          
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/features/move_back.js.erb
<% if @message[:notice].present? %>
	$('#feature-messages').removeClass('alert-danger hidden')
	$('#feature-messages').addClass('alert-success')
	$('#response-message').html('<%= @message[:notice] %>')
	feature = $('.feature_<%= @message[:feature] %>').html()
	$('.feature_<%= @message[:feature] %>').addClass('remove_element')
	$('.feature_<%= @message[:feature] %>').parent('td').prev('td').append('<div class="feature_<%= @message[:feature] %>">'+ feature +'</div>')
	$('.remove_element').remove()
<% else %>
	$('#feature-messages').removeClass('alert-success hidden')
	$('#feature-messages').addClass('alert-danger')
	$('#response-message').html('<%= @message[:alert] %>')
<% end %>

app/views/features/move_forword.js.erb
<% if @message[:notice].present? %>
	$('#feature-messages').removeClass('alert-danger hidden')
	$('#feature-messages').addClass('alert-success')
	$('#response-message').html('<%= @message[:notice] %>')
	feature = $('.feature_<%= @message[:feature] %>').html()
	$('.feature_<%= @message[:feature] %>').addClass('remove_element')
	$('.feature_<%= @message[:feature] %>').parent('td').next('td').append('<div class="feature_<%= @message[:feature] %>">'+ feature +'</div>')
	$('.remove_element').remove()
<% else %>
	$('#feature-messages').removeClass('alert-success hidden')
	$('#feature-messages').addClass('alert-danger')
	$('#response-message').html('<%= @message[:alert] %>')
<% end %>

app/views/features/new.html.erb
<%= render 'form' %>

app/views/features/todo_list.html.erb
<div class="alert alert-success alert-danger alert-dismissable hidden" id="feature-messages">
  <span id="response-message"></span>
</div>
<div class="row">
  <div class="">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>
            Project Name
          </th>
          <th>
            Todo
          </th>
          <th>
            In Progress
          </th>
          <th>
            Done
          </th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <% todo_features =  Feature.by_status_project_developer(project.id, current_employee.id, 'todo') %>
          <% inprogress_features =  Feature.by_status_project_developer(project.id, current_employee.id, 'inprogress') %>
          <% done_features =  Feature.by_status_project_developer(project.id, current_employee.id, 'done') %>
          <tr>
            <td>
              <%= project.title %>
            </td>
            <td>
              <% todo_features.each do |todo| %>
                <dir class="feature_<%= todo.id %>">
                  <%= link_to_if true, 'Backword', move_back_path(todo.id), remote: true %> <%= todo.title %> <%= link_to_if true, 'Forword', move_forword_path(todo.id), remote: true %>
                </dir>
              <% end %>
            </td>
            <td>
              <% inprogress_features.each do |todo| %>
                <dir class="feature_<%= todo.id %>">
                  <%= link_to_if true, 'Backword', move_back_path(todo.id), remote: true %> <%= todo.title %> <%= link_to_if true, 'Forword', move_forword_path(todo.id), remote: true %>
                </dir>
              <% end %>
            </td>
            <td>
              <% done_features.each do |todo| %>
                <dir class="feature_<%= todo.id %>">
                  <%= link_to_if true, 'Backword', move_back_path(todo.id), remote: true %> <%= todo.title %> <%= link_to_if true, 'Forword', move_forword_path(todo.id), remote: true %>
                </dir>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>