config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {registrations: "registrations"}

  root to: 'home#index'
  devise_scope :employee do
    get '/' => 'devise/sessions#new'
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  resources :employees
  resources :projects do
    collection do
      patch :assign_project
    end
    member do
      get :pie_chart
    end
    resources :features
  end

  get '/manager_features_view' => 'features#manager_features_view'
  get '/todo_list' => 'features#todo_list'
  get '/move_forword/:id' => 'features#move_forword', as: :move_forword
  get '/move_back/:id' => 'features#move_back', as: :move_back

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <% if employee_signed_in? %>
        <div class="pull-right margin-bottom-30 margin-top-15">
          <strong><%= current_employee.email %></strong>.
          <%= link_to 'Edit profile', edit_employee_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_employee_session_path, method: :delete, :class => 'navbar-link'  %>
        </div>
        <div class="row margin-bottom-30 margin-top-15">
          <% if can? :manage, :all %>
            <div class="col-md-1">
              <%= link_to 'Employess', employees_path %>
            </div>
            <div class="col-md-1">
              <%= link_to 'Projects', projects_path %>
            </div>
            <dir  class="col-md-1 margin-0">
              <%= link_to 'ToDo List', manager_features_view_path %>
            </dir>
          <% elsif can? :view, :todo_list %>
            <div class="col-md-1">      
              <%= link_to 'ToDo List', todo_list_path %>
            </div>
          <% end %>
        </div>
      <% else %>
        <%= link_to "Sign up", new_employee_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_employee_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    <div class="row">
      <% if notice.present? %><p class="notice alert-success"><%= notice.html_safe %></p><% end %>
      <% if alert.present? %><p class="alert alert-danger"><%= alert.html_safe %></p><% end %>
    </div>
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>